version: '3'
services:
  site:
    depends_on:
      - db
    volumes:
      - C:\projects:/var/www/html
      - C:\docker\apache2/hosts:/etc/apache2/sites-enabled
      - C:\tmp:/tmp
    build: .
    container_name: site
    ports:
      - 80:80
    links:
      - db
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3306:3306
    volumes:
      - C:\docker\mysql:/var/lib/mysql
    environment:
      MYSQL_USER: alex
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123



